// <auto-generated />
using LibraryWeb.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using System;

namespace LibraryWeb.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    partial class LibraryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("LibraryWeb.Model.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<string>("Media");

                    b.Property<bool>("State");

                    b.Property<string>("Title");

                    b.Property<int?>("UserId");

                    b.Property<string>("Year");

                    b.Property<string>("RentedWhen");

                    b.HasKey("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Book");
                });

            modelBuilder.Entity("LibraryWeb.Model.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("ContactNo");

                    b.Property<string>("Email");

                    b.Property<string>("FavouritesCategories");

                    b.Property<bool>("IsAdmin");

                    b.Property<string>("LastName");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<string>("PostCode");

                    b.Property<string>("Street");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LibraryWeb.Model.Book", b =>
                {
                    b.HasOne("LibraryWeb.Model.User")
                        .WithMany("RentedBooks")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
